name:                github-move-issue
version:             0.1.0.0
github:              "LeastAuthority/github-move-issue"
license:             BSD3
author:              "Least Authority TFA GmbH"
maintainer:          "jean-paul@leastauthority.com"
copyright:           "BSD3"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/LeastAuthority/github-move-issue#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - "github"
  - "text"
  - "vector"

executables:
  github-move-issue-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - "text"
    - "github-move-issue"

tests:
  github-move-issue-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - github-move-issue
